# Generated by Django 3.2.4 on 2021-07-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
